#!/usr/bin/env bash
# Persist Codex Agent Pack environment variables in a shell-loadable env file.
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: bash scripts/set-env.sh [--file PATH] [--codex-home PATH] KEY=VALUE [KEY=VALUE ...]

Writes KEY=VALUE pairs to:
  ${CODEX_AGENT_PACK_ENV_FILE:-${CODEX_HOME:-$HOME/.codex}/agent-pack/env.sh}

The generated file is intended to be sourced by Codex Agent Pack skills that
need persisted target configuration, such as devops-github and devops-azure.
USAGE
}

codex_home="${CODEX_HOME:-$HOME/.codex}"
env_file="${CODEX_AGENT_PACK_ENV_FILE:-}"
pairs=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --file)
      env_file="${2:?Missing value for --file}"
      shift 2
      ;;
    --codex-home)
      codex_home="${2:?Missing value for --codex-home}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *=*)
      pairs+=("$1")
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "${#pairs[@]}" -eq 0 ]]; then
  usage >&2
  exit 1
fi

if [[ -z "$env_file" ]]; then
  env_file="$codex_home/agent-pack/env.sh"
fi

keys=()
values=()
for pair in "${pairs[@]}"; do
  key="${pair%%=*}"
  value="${pair#*=}"

  if [[ ! "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    echo "ERROR: invalid environment variable name: $key" >&2
    exit 1
  fi

  keys+=("$key")
  values+=("$value")
done

shell_quote() {
  local value="$1"
  local escaped
  escaped="$(printf '%s' "$value" | sed "s/'/'\\\\''/g")"
  printf "'%s'" "$escaped"
}

mkdir -p "$(dirname -- "$env_file")"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  printf '%s\n' '# Generated by Codex Agent Pack scripts/set-env.sh.'
  printf '%s\n' '# Source this file from shell commands that need persisted pack env.'

  if [[ -f "$env_file" ]]; then
    while IFS= read -r line; do
      case "$line" in
        '# Generated by Codex Agent Pack scripts/set-env.sh.'|'# Source this file from shell commands that need persisted pack env.')
          continue
          ;;
      esac

      keep=1
      for key in "${keys[@]}"; do
        if [[ "$line" =~ ^(export[[:space:]]+)?${key}= ]]; then
          keep=0
          break
        fi
      done

      if [[ "$keep" -eq 1 && -n "$line" ]]; then
        printf '%s\n' "$line"
      fi
    done < "$env_file"
  fi

  for i in "${!keys[@]}"; do
    printf 'export %s=%s\n' "${keys[$i]}" "$(shell_quote "${values[$i]}")"
  done
} > "$tmp_file"

mv -- "$tmp_file" "$env_file"
trap - EXIT

for i in "${!keys[@]}"; do
  echo "[ok] env: ${keys[$i]}=${values[$i]}"
done
echo "[ok] wrote: $env_file"
